version: '3.9'

services:
  delivery-db:
    container_name: delivery-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pduser
      - POSTGRES_PASSWORD=pduserpass
      - POSTGRES_DB=delivery
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - '5432:5432'
    networks:
      - ms-network

  auth-ms:
    container_name: auth-ms
    image: auth-ms
    build:
      context: auth-ms
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - delivery-db
    networks:
      - ms-network

  customer-ms:
    container_name: customer-ms
    image: customer-ms
    build:
      context: customer-ms
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - delivery-db
    networks:
      - ms-network

  courier-ms:
    container_name: courier-ms
    image: courier-ms
    build:
      context: courier-ms
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - delivery-db
    networks:
      - ms-network

  delivery-ms:
    container_name: delivery-ms
    image: delivery-ms
    build:
      context: delivery-ms
      dockerfile: ./Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - delivery-db
    networks:
      - ms-network

networks:
    ms-network:
        driver: bridge
