server:
  port: 8080
  servlet:
    context-path: /delivery-ms

spring:
  application:
    name: delivery-ms

  datasource:
    url: jdbc:postgresql://delivery-db:5432/delivery
    username: pduser
    password: pduserpass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml
    drop-first: false
    default-schema: public
    database-change-log-table: MS_DELIVERY_DBCHANGELOG
    database-change-log-lock-table: MS_DELIVERY_DBCHANGELOGLOCK

springdoc:
  swagger-ui:
    path: /swagger

application:
  jwt:
    secretKey: supersecretkeywhichisnotsecretsupersecretkeywhichisnotsecretsupersecretkeywhichisnotsecret
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 10
    authorizationHeader: Authorization

feignclient:
  courier-ms: http://localhost:8080/courier-ms

logging.level.com.guava.deliveryms.client: DEBUG




